spring:
  security:
    oauth2:
      client:
        registration:
          oauth2-client:
            provider: spotify
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:1984/login/oauth2/code/spotify
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope:
              - user-read-private
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id